package dev.mcoder.etl.sample;

import java.math.BigDecimal;
import java.time.LocalDate;

import dev.mcoder.etl.pojospreadsheet.annotation.SheetCol;
import dev.mcoder.etl.pojospreadsheet.validation.constraints.NoFormula;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PastOrPresent;
import jakarta.validation.constraints.Pattern;

/**
 * JPA entity that doubles as the spreadsheet row: each {@code @SheetCol} field maps to one column
 * of the import/export file. {@code id} has no {@code @SheetCol}, so it is generated by the
 * database and left out of the file.
 */
@Entity
public class Employee {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @SheetCol(value = "A", label = "Employee ID")
    @NotBlank
    @Pattern(regexp = "EMP-\\d{5}", message = "must match EMP-00000")
    @Column(nullable = false, unique = true, length = 9)
    private String employeeId;

    @SheetCol(value = "B", label = "Full name")
    @NotBlank
    @NoFormula
    @Column(nullable = false)
    private String fullName;

    @SheetCol(value = "C", label = "Email")
    @NotBlank
    @Email
    @Column(nullable = false)
    private String email;

    @SheetCol(value = "D", label = "Age")
    @NotNull
    @Min(18)
    private Integer age;

    @SheetCol(value = "E", label = "Salary")
    @DecimalMin("0")
    private BigDecimal salary;

    @SheetCol(value = "F", label = "Join date")
    @PastOrPresent
    private LocalDate joinDate;

    @SheetCol(value = "G", label = "Status")
    @NotNull
    @Enumerated(EnumType.STRING)
    private Status status;

    public enum Status {
        ACTIVE, ON_LEAVE, TERMINATED
    }

    protected Employee() {
        // required by JPA and by SpreadsheetReader
    }

    public Employee(String employeeId, String fullName, String email, Integer age, BigDecimal salary,
            LocalDate joinDate, Status status) {
        this.employeeId = employeeId;
        this.fullName = fullName;
        this.email = email;
        this.age = age;
        this.salary = salary;
        this.joinDate = joinDate;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public String getEmployeeId() {
        return employeeId;
    }

    public String getFullName() {
        return fullName;
    }

    public String getEmail() {
        return email;
    }

    public Integer getAge() {
        return age;
    }

    public BigDecimal getSalary() {
        return salary;
    }

    public LocalDate getJoinDate() {
        return joinDate;
    }

    public Status getStatus() {
        return status;
    }
}
